- name: Install redis
  apt:
    name: redis-server
    state: present

- name: Set up redis
  template:
    src: ../files/redis.conf
    dest: /etc/redis/redis.conf

- name: start redis
  systemd_service:
    name: redis-server
    state: started
    enabled: yes
